name: Restart Toolforge services

on:
  - workflow_dispatch

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/toolforge.key
          chmod 600 ~/.ssh/toolforge.key
          cat >> ~/.ssh/config <<END
          Host toolforge
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/toolforge.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: mdaniels5757
          SSH_KEY: ${{ secrets.TOOLFORGE_PRIVATE_KEY }}
          SSH_HOST: login.toolforge.org

      - name: Restart the server
        run: >-
            ssh toolforge become mdanielsbot bash -c '
              cd /data/project/mdanielsbot/MD-SDZeroBot/webservice && npm restart;
              cd /data/project/mdanielsbot/MD-SDZeroBot/eventstream-router && npm restart;
            '
      - name: Cleanup SSH
        run: rm -rf .ssh