name: Toolforge

on:
#   push:
#     branches:
#       - master
  workflow_dispatch:

concurrency:
  group: tf-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: appleboy/ssh-action@551964ebda1034f0b5449d74db25c42e371ca1f7
        with:
          script: >-
            become mdanielsbot bash -c '
              set -eo pipefail;
              export NVM_DIR="$HOME/.nvm";
              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh";
              [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion";
              nvm use default;
              cd /data/project/mdanielsbot/mwn;
              if [[ "$(git pull --ff-only | grep -c "Already up to date")" -eq 0 ]]; then
                if [[ "$(git diff --name-only HEAD HEAD@{1} | grep -c package.json)" -gt 0 ]]; then
                  echo "Running npm install for mwn ...";
                  npm install;
                fi;
                echo "Building mwn ...";
                npm run build;
              fi;
              cd /data/project/mdanielsbot/MD-SDZeroBot;
              echo "Pulling SDZeroBot ...";
              git checkout master;
              git pull --ff-only;
              if [[ "$(git diff --name-only HEAD HEAD@{1} | grep -c package.json)" -gt 0 ]]; then
                echo "Running npm install for SDZeroBot ...";
                npm install;
              fi;
              echo "Building SDZeroBot ...";
              npm run tsc;
              echo "Updating jobs.yml ...";
              toolforge jobs load jobs.yml;
              if [[ "$(git diff --name-only HEAD HEAD@{1} | grep -c eventstream)" -gt 0 || "$(git rev-list --format=%B --max-count=1 HEAD)" == *"!restart"* ]]; then
                echo "Restarting eventstream-router ...";
                cd eventstream-router && npm restart && cd -;
              fi;
              cp webservice/www-js-package.json /data/project/mdanielsbot/www/js/package.json;
              if [[ "$(git diff --name-only HEAD HEAD@{1} | grep -c "webservice/")" -gt 0 || "$(git diff --name-only HEAD HEAD@{1} | grep -c "web-endpoint")" -gt 0 || "$(git diff --name-only HEAD HEAD@{1} | grep -c "hbs")" -gt 0 || "$(git rev-list --format=%B --max-count=1 HEAD)" == *"!restart"* || "$(git rev-list --format=%B --max-count=1 HEAD)" == *"!web-restart"* ]]; then
                echo "Restarting SDZeroBot webservice ...";
                cd /data/project/mdanielsbot/MD-SDZeroBot/webservice && npm restart && cd -;
              fi;
              toolforge jobs restart db-tabulator;
              toolforge jobs restart shells;
            '
          host: login.toolforge.org
          username: mdaniels5757
          key: ${{ secrets.TOOLFORGE_PRIVATE_KEY }}
